#!/bin/bash
shopt -s nocasematch

BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
BRANCH_REGEX="^([0-9]+)"
COMMIT_MSG=$(cat $1)
COMMIT_REGEX="Related-work-items"

if [ -n "$BRANCH_NAME" ] && ! [[ $COMMIT_MSG =~ $COMMIT_REGEX ]] && [[ $BRANCH_NAME =~ $BRANCH_REGEX ]]; then
    sed -i.bak -e "1s/^#${BASH_REMATCH[1]}: //I" $1
    sed -i.bak -e "1s/$/\n\nRelated-work-items: #${BASH_REMATCH[1]}/" $1
fi
